# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Fri Jun 12 00:26:06 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1061, 659)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 401))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rate1 = QtGui.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rate1.sizePolicy().hasHeightForWidth())
        self.rate1.setSizePolicy(sizePolicy)
        self.rate1.setAccelerated(True)
        self.rate1.setMinimum(1)
        self.rate1.setMaximum(1000)
        self.rate1.setSingleStep(5)
        self.rate1.setProperty("value", 300)
        self.rate1.setObjectName(_fromUtf8("rate1"))
        self.gridLayout.addWidget(self.rate1, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.rate2 = QtGui.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rate2.sizePolicy().hasHeightForWidth())
        self.rate2.setSizePolicy(sizePolicy)
        self.rate2.setAccelerated(True)
        self.rate2.setMinimum(1)
        self.rate2.setMaximum(1000)
        self.rate2.setSingleStep(5)
        self.rate2.setProperty("value", 300)
        self.rate2.setObjectName(_fromUtf8("rate2"))
        self.gridLayout.addWidget(self.rate2, 1, 1, 1, 1)
        self.rate3 = QtGui.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rate3.sizePolicy().hasHeightForWidth())
        self.rate3.setSizePolicy(sizePolicy)
        self.rate3.setAccelerated(True)
        self.rate3.setMinimum(1)
        self.rate3.setMaximum(1000)
        self.rate3.setSingleStep(5)
        self.rate3.setProperty("value", 300)
        self.rate3.setObjectName(_fromUtf8("rate3"))
        self.gridLayout.addWidget(self.rate3, 2, 1, 1, 1)
        self.rate4 = QtGui.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rate4.sizePolicy().hasHeightForWidth())
        self.rate4.setSizePolicy(sizePolicy)
        self.rate4.setAccelerated(True)
        self.rate4.setMinimum(1)
        self.rate4.setMaximum(1000)
        self.rate4.setSingleStep(5)
        self.rate4.setProperty("value", 300)
        self.rate4.setObjectName(_fromUtf8("rate4"))
        self.gridLayout.addWidget(self.rate4, 3, 1, 1, 1)
        self.rate5 = QtGui.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rate5.sizePolicy().hasHeightForWidth())
        self.rate5.setSizePolicy(sizePolicy)
        self.rate5.setAccelerated(True)
        self.rate5.setMinimum(1)
        self.rate5.setMaximum(1000)
        self.rate5.setSingleStep(5)
        self.rate5.setProperty("value", 300)
        self.rate5.setObjectName(_fromUtf8("rate5"))
        self.gridLayout.addWidget(self.rate5, 4, 1, 1, 1)
        self.rate6 = QtGui.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rate6.sizePolicy().hasHeightForWidth())
        self.rate6.setSizePolicy(sizePolicy)
        self.rate6.setAccelerated(True)
        self.rate6.setMinimum(1)
        self.rate6.setMaximum(1000)
        self.rate6.setSingleStep(5)
        self.rate6.setProperty("value", 300)
        self.rate6.setObjectName(_fromUtf8("rate6"))
        self.gridLayout.addWidget(self.rate6, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.pulsestat = QtGui.QPlainTextEdit(self.verticalLayoutWidget)
        self.pulsestat.setReadOnly(True)
        self.pulsestat.setObjectName(_fromUtf8("pulsestat"))
        self.verticalLayout.addWidget(self.pulsestat)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(740, 90, 301, 141))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.spectrumstat = QtGui.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.spectrumstat.setReadOnly(True)
        self.spectrumstat.setObjectName(_fromUtf8("spectrumstat"))
        self.verticalLayout_2.addWidget(self.spectrumstat)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 430, 351, 71))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.test1 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.test1.setObjectName(_fromUtf8("test1"))
        self.gridLayout_3.addWidget(self.test1, 0, 0, 1, 1)
        self.test2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.test2.setObjectName(_fromUtf8("test2"))
        self.gridLayout_3.addWidget(self.test2, 0, 1, 1, 1)
        self.test4 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.test4.setObjectName(_fromUtf8("test4"))
        self.gridLayout_3.addWidget(self.test4, 1, 0, 1, 1)
        self.test5 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.test5.setObjectName(_fromUtf8("test5"))
        self.gridLayout_3.addWidget(self.test5, 1, 1, 1, 1)
        self.test6 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.test6.setObjectName(_fromUtf8("test6"))
        self.gridLayout_3.addWidget(self.test6, 1, 2, 1, 1)
        self.test3 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.test3.setObjectName(_fromUtf8("test3"))
        self.gridLayout_3.addWidget(self.test3, 0, 2, 1, 1)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 510, 351, 80))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.voltageoff = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.voltageoff.setObjectName(_fromUtf8("voltageoff"))
        self.gridLayout_4.addWidget(self.voltageoff, 0, 1, 1, 1)
        self.voltagemax = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.voltagemax.setObjectName(_fromUtf8("voltagemax"))
        self.gridLayout_4.addWidget(self.voltagemax, 0, 0, 1, 1)
        self.spectrumpulse = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.spectrumpulse.setObjectName(_fromUtf8("spectrumpulse"))
        self.gridLayout_4.addWidget(self.spectrumpulse, 1, 0, 1, 1)
        self.testtrigger = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.testtrigger.setObjectName(_fromUtf8("testtrigger"))
        self.gridLayout_4.addWidget(self.testtrigger, 1, 1, 1, 1)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(400, 280, 641, 311))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.plotspace = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.plotspace.setMargin(0)
        self.plotspace.setObjectName(_fromUtf8("plotspace"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(570, 0, 251, 81))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 231, 33))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.run = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.run.setObjectName(_fromUtf8("run"))
        self.gridLayout_2.addWidget(self.run, 0, 0, 1, 1)
        self.stop = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.stop.setObjectName(_fromUtf8("stop"))
        self.gridLayout_2.addWidget(self.stop, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(14, 10, 221, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(400, 90, 331, 141))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.spectrumrate = QtGui.QSpinBox(self.verticalLayoutWidget_4)
        self.spectrumrate.setMaximum(1000)
        self.spectrumrate.setSingleStep(5)
        self.spectrumrate.setProperty("value", 100)
        self.spectrumrate.setObjectName(_fromUtf8("spectrumrate"))
        self.gridLayout_5.addWidget(self.spectrumrate, 0, 1, 1, 1)
        self.spectrumlistrefresh = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.spectrumlistrefresh.setObjectName(_fromUtf8("spectrumlistrefresh"))
        self.gridLayout_5.addWidget(self.spectrumlistrefresh, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.spectrumlist = QtGui.QComboBox(self.verticalLayoutWidget_4)
        self.spectrumlist.setObjectName(_fromUtf8("spectrumlist"))
        self.verticalLayout_3.addWidget(self.spectrumlist)
        self.spectrumline = QtGui.QLineEdit(self.centralwidget)
        self.spectrumline.setGeometry(QtCore.QRect(400, 240, 431, 33))
        self.spectrumline.setObjectName(_fromUtf8("spectrumline"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1061, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MeasureSim", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Pulse Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Channel 2 Rate (1/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Channel 1 Rate (1/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Channel 4 Rate (1/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Channel 5 Rate (1/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Channel 3 Rate (1/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Channel 6 Rate (1/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Pulse Statistics:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Spectrum Stats:", None, QtGui.QApplication.UnicodeUTF8))
        self.test1.setText(QtGui.QApplication.translate("MainWindow", "Test Ch. 1", None, QtGui.QApplication.UnicodeUTF8))
        self.test2.setText(QtGui.QApplication.translate("MainWindow", "Test Ch. 2", None, QtGui.QApplication.UnicodeUTF8))
        self.test4.setText(QtGui.QApplication.translate("MainWindow", "Test Ch. 4", None, QtGui.QApplication.UnicodeUTF8))
        self.test5.setText(QtGui.QApplication.translate("MainWindow", "Test Ch. 5", None, QtGui.QApplication.UnicodeUTF8))
        self.test6.setText(QtGui.QApplication.translate("MainWindow", "Test Ch. 6", None, QtGui.QApplication.UnicodeUTF8))
        self.test3.setText(QtGui.QApplication.translate("MainWindow", "Test Ch. 3", None, QtGui.QApplication.UnicodeUTF8))
        self.voltageoff.setText(QtGui.QApplication.translate("MainWindow", "Set Output Off (0V)", None, QtGui.QApplication.UnicodeUTF8))
        self.voltagemax.setText(QtGui.QApplication.translate("MainWindow", "Set Output Max (5V)", None, QtGui.QApplication.UnicodeUTF8))
        self.spectrumpulse.setText(QtGui.QApplication.translate("MainWindow", "Single Pulse (Max, 5V)", None, QtGui.QApplication.UnicodeUTF8))
        self.testtrigger.setText(QtGui.QApplication.translate("MainWindow", "Test Trigger Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.run.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Main Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Spectrum Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Spectrum Rate (1/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.spectrumlistrefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Select Spectrum:", None, QtGui.QApplication.UnicodeUTF8))

